FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

FROM node:24-alpine AS deps

WORKDIR /app

COPY package*.json .

RUN npm ci --omit=dev


FROM gcr.io/distroless/nodejs22-debian12

WORKDIR /app

COPY --from=build /app/build ./build
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/package*.json .

EXPOSE 3000

CMD ["node_modules/@react-router/serve/bin.js", "./build/server/index.js"]

